cmake_minimum_required(VERSION 3.17)
project(Assignment16 CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(ex02_sms_cost          ex02_sms_cost.cpp)
add_executable(ex05_array_occurrences ex05_array_occurrences.cpp)
add_executable(ex07_digit_sum         ex07_digit_sum.cpp)
