cmake_minimum_required(VERSION 3.17)
project(Assignment09 CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(ex02_product_discount ex02_product_discount.cpp)
add_executable(ex06_sales_analysis   ex06_sales_analysis.cpp)
add_executable(ex08_teacher_salary   ex08_teacher_salary.cpp)
