namespace KnuthSolver.Models;

/// <summary>
/// A node in the search tree for Knuth's conjecture.
///
/// The numeric state is stored as a <see cref="double"/>. A state is considered
/// a whole number when it differs from the nearest integer by less than 1e-8,
/// consistent with the original BigDecimal-based implementation.
/// </summary>
internal sealed class SearchNode
{
    private const double IntegerTolerance = 1e-8;
    private const double FactorialLimit   = 9999.0;

    /// <summary>Current numeric value of this search state.</summary>
    public double State { get; }

    /// <summary>Parent node, or <c>null</c> for the root.</summary>
    public SearchNode? Parent { get; }

    /// <summary>Child nodes generated by <see cref="ExpandNode"/>.</summary>
    public List<SearchNode> Children { get; } = [];

    /// <summary>Name of the operation that produced this node ("factorial", "sqrt", "floor", or "" for root).</summary>
    public string Move { get; set; } = string.Empty;

    /// <summary>Depth of this node in the search tree (root = 0).</summary>
    public int Depth { get; }

    /// <summary>Returns <c>true</c> when the state is a whole number.</summary>
    public bool IsWholeNumber =>
        Math.Abs(State - Math.Round(State)) < IntegerTolerance;

    /// <summary>Initialises a node with a given numeric state.</summary>
    public SearchNode(double state, SearchNode? parent, string move = "")
    {
        State  = state;
        Parent = parent;
        Move   = move;
        Depth  = ComputeDepth();
    }

    /// <summary>Returns <c>true</c> when this state matches <paramref name="goal"/>.</summary>
    public bool IsGoal(double goal) =>
        Math.Abs(State - goal) < IntegerTolerance;

    /// <summary>
    /// Generates all valid successor states and adds them to <see cref="Children"/>.
    ///
    /// Rules (Knuth's conjecture operations):
    /// <list type="bullet">
    ///   <item>Factorial  — only when the state is a whole number and &lt; 9999.</item>
    ///   <item>Floor      — only when the state is fractional.</item>
    ///   <item>Square root — always.</item>
    /// </list>
    /// </summary>
    public void ExpandNode()
    {
        if (IsWholeNumber && State < FactorialLimit)
            Children.Add(new SearchNode(Factorial((int)Math.Round(State)), this, "factorial"));

        if (!IsWholeNumber)
            Children.Add(new SearchNode(Math.Floor(State), this, "floor"));

        Children.Add(new SearchNode(RoundTo3SignificantFigures(Math.Sqrt(State)), this, "sqrt"));
    }

    // ── private helpers ──────────────────────────────────────────────────────

    private static double Factorial(int n)
    {
        double result = 1;
        for (int i = 2; i <= n; i++)
            result *= i;
        return result;
    }

    /// <summary>Rounds to 3 significant figures (matches Java's MathContext(3)).</summary>
    private static double RoundTo3SignificantFigures(double value)
    {
        if (value == 0) return 0;
        double scale = Math.Pow(10, 3 - Math.Floor(Math.Log10(Math.Abs(value))) - 1);
        return Math.Round(value * scale) / scale;
    }

    private int ComputeDepth()
    {
        int depth = 0;
        var node = Parent;
        while (node is not null) { depth++; node = node.Parent; }
        return depth;
    }
}
