"""Search tree node for Peg Solitaire."""

import copy
import logging
from itertools import chain
from typing import Optional

logger = logging.getLogger(__name__)

# A move encodes source (x, y) and destination (x', y') in board coordinates.
Move = dict[str, int]


class SearchNode:
    """A node in the peg solitaire search tree.

    Attributes:
        state: 2-D grid where '1' represents a peg and '2' an empty hole.
        parent: Parent node, or None for the root.
        children: Successor nodes generated by :meth:`expand`.
        move: Dict with keys 'x', 'y', "x'", "y'" describing this node's move.
        heuristic_score: Remaining peg count used by Best-First Search (lower is better).
    """

    def __init__(self, state: list[list[str]], parent: Optional["SearchNode"]) -> None:
        self.state = state
        self.parent = parent
        self.children: list[SearchNode] = []
        self.move: Move = {}
        self.heuristic_score: int = self._count_pegs()

    # ── public interface ───────────────────────────────────────────────────────

    def win(self) -> bool:
        """Return True when exactly one peg remains on the board."""
        return list(chain.from_iterable(self.state)).count("1") == 1

    def expand(self) -> None:
        """Generate all valid successor states and append them to :attr:`children`."""
        board = self.state
        rows = len(board)
        cols = len(board[1]) if rows > 1 else 0

        # Preserve original loop bounds (rows-1, cols-2) from the assignment.
        for i in range(rows - 1):
            for j in range(cols - 2):
                self._check_horizontal(board, i, j)
                self._check_vertical_up(board, i, j)
                self._check_vertical_down(board, i, j, rows)

    # ── private helpers ────────────────────────────────────────────────────────

    def _apply_move(self, move: Move, between: Move) -> "SearchNode":
        """Deep-copy the board, apply the move, and return a new child node."""
        new_state = copy.deepcopy(self.state)
        new_state[move["x"]][move["y"]] = "2"
        new_state[between["x"]][between["y"]] = "2"
        new_state[move["x'"]][move["y'"]] = "1"
        child = SearchNode(new_state, self)
        child.move = move
        return child

    def _check_horizontal(self, board: list[list[str]], i: int, j: int) -> None:
        """Check and generate left/right horizontal moves from (i, j)."""
        if board[i][j] != "1" or board[i][j + 1] != "1":
            return

        # Move left: peg at (i, j+1) jumps over (i, j) to land at (i, j-1).
        # NOTE: board[i][j-1] when j=0 accesses the last column (Python wrap-around),
        # but the j-1>=0 guard prevents the move from being registered.
        if board[i][j - 1] == "2" and j - 1 >= 0:
            self.children.append(self._apply_move(
                move={"x": i, "y": j + 1, "x'": i, "y'": j - 1},
                between={"x": i, "y": j},
            ))

        # Move right: peg at (i, j) jumps over (i, j+1) to land at (i, j+2).
        if board[i][j + 2] == "2":
            self.children.append(self._apply_move(
                move={"x": i, "y": j, "x'": i, "y'": j + 2},
                between={"x": i, "y": j + 1},
            ))

    def _check_vertical_up(self, board: list[list[str]], i: int, j: int) -> None:
        """Check and generate an upward vertical move from (i, j)."""
        if board[i][j] == "1" and board[i - 1][j] == "1" and i - 2 >= 0:
            if board[i - 2][j] == "2":
                self.children.append(self._apply_move(
                    move={"x": i, "y": j, "x'": i - 2, "y'": j},
                    between={"x": i - 1, "y": j},
                ))

    def _check_vertical_down(
        self, board: list[list[str]], i: int, j: int, rows: int
    ) -> None:
        """Check and generate a downward vertical move from (i, j)."""
        if board[i][j] == "1" and board[i + 1][j] == "1" and i + 2 <= rows - 1:
            if board[i + 2][j] == "2":
                self.children.append(self._apply_move(
                    move={"x": i, "y": j, "x'": i + 2, "y'": j},
                    between={"x": i + 1, "y": j},
                ))

    def _count_pegs(self) -> int:
        return list(chain.from_iterable(self.state)).count("1")
