"""FreeCell game state modelled as a search tree node."""

import copy
import logging
from typing import Optional

logger = logging.getLogger(__name__)

Card = str           # e.g. "H1", "S13", "D7"
Pile = list[Card]    # ordered stack, top card last


class GameState:
    """A node in the FreeCell search tree.

    The game consists of three zones:
    - **Tableau** — 8 stacks of cards dealt at the start.
    - **Free cells** — 4 temporary holding slots (None when empty).
    - **Foundation** — 4 suit stacks built in ascending order (A → K).

    Attributes:
        tableau: Current tableau stacks (list of 8 piles).
        free_cells: The 4 free cell slots.
        foundation: The 4 foundation piles, initialised with a sentinel (e.g. "H0").
        parent: Parent node, or None for the root.
        children: Child nodes generated by :meth:`expand`.
        move: String describing the operation that produced this node.
        heuristic_score: Best-First heuristic (lower = closer to goal).
        a_score: A* score (heuristic + depth).
    """

    def __init__(
        self,
        tableau: list[Pile],
        foundation: list[Pile],
        free_cells: list[Optional[Card]],
        parent: Optional["GameState"],
    ) -> None:
        self.tableau = tableau
        self.foundation = foundation
        self.free_cells = free_cells
        self.parent = parent
        self.children: list[GameState] = []
        self.move: str = ""
        self.heuristic_score: float = self._best_first_score()
        self.a_score: float = self._a_star_score()

    # ── win condition ──────────────────────────────────────────────────────────

    def check_if_win(self) -> bool:
        """Return True when every foundation pile has been completed (13 cards)."""
        result = all(pile[-1][1:] == "13" for pile in self.foundation)
        if result:
            logger.info("Win condition reached.")
        return result

    # ── state serialisation (for visited-set deduplication) ───────────────────

    def value_to_str(self) -> str:
        """Serialise the full game state to a single string for cycle detection."""
        free = "".join(c if c else "None" for c in self.free_cells)

        foundation = ""
        for pile in self.foundation:
            foundation += "None" if int(pile[-1][1:]) == 0 else "".join(pile)

        tableau = ""
        for pile in self.tableau:
            tableau += "".join(pile) if pile else "None"

        return free + foundation + tableau

    # ── node expansion ─────────────────────────────────────────────────────────

    def expand(self) -> list[str]:
        """Generate all valid successor states.

        Returns:
            Parallel list of move description strings (same length as :attr:`children`).
        """
        all_moves: list[str] = []

        for idx, pile in enumerate(self.tableau):
            if not pile:
                continue
            card = pile[-1]
            self._try_foundation(card, idx, source="Tableau", moves=all_moves)
            self._try_pile(card, idx, source="Tableau", moves=all_moves)
            self._try_free_cell(card, idx, moves=all_moves)

        for idx, card in enumerate(self.free_cells):
            if card is None:
                continue
            self._try_foundation(card, idx, source="freeCell", moves=all_moves)
            self._try_pile(card, idx, source="freeCell", moves=all_moves)

        return all_moves

    # ── private move generators ────────────────────────────────────────────────

    def _try_free_cell(self, card: Card, src_idx: int, moves: list[str]) -> None:
        for i, cell in enumerate(self.free_cells):
            if cell is None:
                child_f, child_fc, child_t = self._deep_copy_zones()
                child_fc[i] = card
                child_t[src_idx].pop()
                child = GameState(child_t, child_f, child_fc, self)
                self.children.append(child)
                moves.append(f"freecell {card}")
                return  # only one free cell needed per card

    def _try_foundation(
        self, card: Card, src_idx: int, source: str, moves: list[str]
    ) -> None:
        suit, value = card[:1], int(card[1:])
        for i, pile in enumerate(self.foundation):
            top_value = int(pile[-1][1:])
            top_suit = pile[-1][:1]
            goes_on_empty = top_value == 0 and top_suit == suit and value == 1
            goes_on_top = top_suit == suit and top_value == value - 1

            if goes_on_empty or goes_on_top:
                child_f, child_fc, child_t = self._deep_copy_zones()
                if goes_on_empty:
                    child_f[i].pop()  # remove sentinel
                child_f[i].append(card)
                if source == "Tableau":
                    child_t[src_idx].pop()
                else:
                    child_fc[src_idx] = None
                child = GameState(child_t, child_f, child_fc, self)
                self.children.append(child)
                moves.append(f"source {card}")
                return  # card goes to exactly one foundation pile

    def _try_pile(
        self, card: Card, src_idx: int, source: str, moves: list[str]
    ) -> None:
        card_suit, card_value = card[:1], int(card[1:])
        for i, pile in enumerate(self.tableau):
            empty_slot = not pile
            fits_on_top = (
                pile
                and pile[-1][:1] != card_suit
                and int(pile[-1][1:]) == card_value + 1
            )
            if not (empty_slot or fits_on_top):
                continue

            child_f, child_fc, child_t = self._deep_copy_zones()
            old_top = pile[-1] if pile else None
            child_t[i].append(card)
            if source == "Tableau":
                child_t[src_idx].pop()
            else:
                child_fc[src_idx] = None
            child = GameState(child_t, child_f, child_fc, self)
            self.children.append(child)
            moves.append("newstack " + card if old_top is None else f"stack {card} {old_top}")

    def _deep_copy_zones(
        self,
    ) -> tuple[list[Pile], list[Optional[Card]], list[Pile]]:
        return (
            copy.deepcopy(self.foundation),
            copy.deepcopy(self.free_cells),
            copy.deepcopy(self.tableau),
        )

    # ── heuristics ─────────────────────────────────────────────────────────────

    def _best_first_score(self) -> float:
        """h(n) = cards_in_tableau + cards_in_free_cells - cards_in_foundation - completed_piles - (cards_in_foundation / 4)."""
        cards_f = sum(
            len(p) for p in self.foundation if p and int(p[-1][1:]) != 0
        )
        completed = sum(
            1 for p in self.foundation if p and int(p[-1][1:]) != 0
        )
        cards_t = sum(len(p) for p in self.tableau)
        cards_fc = sum(1 for c in self.free_cells if c)
        return cards_t + cards_fc - cards_f - completed - (cards_f / 4)

    def _a_star_score(self) -> float:
        """f(n) = h(n) + g(n) where g(n) is the node depth."""
        depth, node = 0, self.parent
        while node:
            depth += 1
            node = node.parent
        self.depth = depth
        return self.heuristic_score + depth
