cmake_minimum_required(VERSION 3.17)
project(Assignment13 CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(ex03_harmonic_number ex03_harmonic_number.cpp)
add_executable(ex05_random_matrix   ex05_random_matrix.cpp)
add_executable(ex06_digit_analysis  ex06_digit_analysis.cpp)
